### ISSUE TITLE
router-link is deprecated

### ISSUE THREAD

**Issue by maltegrosse** [nejinn/nly-adminlte-vue#119]
vue js throws following error:
`<router-link>'s tag prop is deprecated and has been removed in Vue Router 4. Use the v-slot API to remove this warning: https://next.router.vuejs.org/guide/migration/#removal-of-event-and-tag-props-in-router-link.`

**Comment by nejinn** [comment]
I'm sorry
```
Most of Vue Router API has remained unchanged during its rewrite from v3 (for Vue 2) to v4 (for Vue 3)
```

you must use it with Vue 2

[click this for more detail ](https://next.router.vuejs.org/guide/migration/index.html#new-history-option-to-replace-mode)

Maybe I'll solve it next version

good luck
