### ISSUE TITLE
keep side-nav collapsed during start

### ISSUE THREAD

**Issue by maltegrosse** [nejinn/nly-adminlte-vue#124]
Hi there,

how to keep the sidebar closed during first render?

**Comment by nejinn** [comment]
Hi：

you can set prop  `visible` false closed the sidebar during first render if you use `nly-sidebar-nav-tree`

[clik for docs](http://nly-adminlte-vue.nejinn.com/docs/components/sidebar)

good luck !

**Comment by maltegrosse** [comment]
thanks for the hint - but actually I want to collapse the whole sidebar.
currently - as a workaround - I fire a manual "click" on the "v-nly-sidebar-collapse.sidebar-collapse" after mounted.
any better way to achieve this?

**Comment by nejinn** [comment]
sorry! 
if you use component  `nly-sidebar-container`, you can set prop `side-mini`  true . the sidebar will  closed the sidebar during first render.
![2](https://user-images.githubusercontent.com/31615794/119266711-6be2d280-bc1e-11eb-9bbb-a32cde6b5fd0.jpg)

if you use component `nly-sidebar-menu`， you can set prop `side-mini` ture , the sidebar will  closed the sidebar during first render.

![1](https://user-images.githubusercontent.com/31615794/119266706-67b6b500-bc1e-11eb-90ff-f203bec4c0d2.jpg)


good luck !

**Comment by maltegrosse** [comment]
thank for the hint. 
but I want to achieve something different: I want to collapse the sidebar to mini on first rendering.

**Comment by nejinn** [comment]
sorry!

it is too hard for me to say with english
you can see the code：
https://github.com/nejinn/nly-adminlte-vue/blob/master/src/directives/sidebar-collapse/sidebar-collapse.js
https://github.com/nejinn/nly-adminlte-vue/blob/0e1891be859380fa2c7a28f9b757c07efc9bf192/src/utils/sidebar-collapse.js#L44

just like this, Put the following code in anywhere you need

```js
mouted(){
  const bodyClassName = document.body.className

  if (bodyClassName.indexOf('sidebar-collapse') == -1) {   
    document.body.classList.add('sidebar-collapse');  
  } 
}

```

good luck
