### ISSUE TITLE
再封装个table的插件就完美了。

### ISSUE THREAD

**Issue by smarttang** [nejinn/nly-adminlte-vue#2]
比如，datatables或者bootstraptable都行。
我目前还没翻到好用的。感谢！

**Comment by nejinn** [comment]
我本来不打算封装table了，github有很多，那我这两天封装一个table吧。很多组件还在封装，请关注。

**Comment by smarttang** [comment]
牛逼啊。。我没想到你会回我来着。。
加油啊！封装完这个挺完整的了。。
